# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - tech0-gen-8-step4-eyesmile-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Debug directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
      - name: Create virtual environment
        run: |
          echo "Creating virtual environment..."
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install pymysql==1.1.0
          pip install -r requirements.txt
          pip install gunicorn uvicorn
          deactivate
        
      - name: Create startup command
        run: |
          echo "gunicorn src.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --timeout 120 --access-logfile - --error-logfile - --log-level info" > startup.txt

      - name: Zip artifact for deployment
        run: |
          echo "Current directory before zip:"
          pwd
          ls -la
          zip -r release.zip * antenv/

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tech0-gen-8-step4-eyesmile-back'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF469CC90E8542E7B952692CDAE114A4 }}
          package: .